# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170806_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomphoto',
            old_name='about',
            new_name='say_something',
        ),
    ]
