# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_albumcomment_randomphotocomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='album_logo'),
        ),
    ]
