# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170913_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='about_photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='randomphoto',
            name='say_something',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
